### PR TITLE
net: gem: Add reset-gpios as an optional property

### PR DESCRIPTION
**Pull request by Livius90**
Hi,

At the moment, in current u-boot implementation there is no any support to use "reset-gpios" functionality for Zynq ethernet from device-tree GEM node like it is supported in Linux kernel. On a 3rd party  ZynqMP board, I was faced with the fact that this is absolutely necessary, because it seems to me that starting from Yocto Xilinx v2020.X ethernet reset pin wasn't released in fsbl stage. It was my experiences for my ZynqMP and it was also reported in a [topic in Xilinx forum](https://support.xilinx.com/s/question/0D52E000076tayOSAQ/cant-find-ksz9031-in-petalinux-20212?language=en_US).

So in u-boot and later at booting time of Linux kernel, Pyh IC is in reset state constantly forever, and it is unavailable and not possible to be initialized at the specific bus address. In Linux side there is a nice solution in the device-tree, the following code can solve it with set up the "reset-gpios" property of GEM node, but it is working only for Linux, u-boot is not ready to parse it from device-tree and performs that optional reset and release.

```C
&gem3 {
    phy-mode = "rgmii-id";
    phy-handle = <&phy0>;
    local-mac-address = [00 0a 35 00 22 01];
    status = "okay";
 
    // reset-gpios = <&gpio 38 GPIO_ACTIVE_LOW>;
    reset-gpios = <&gpio 38 1>;
    reset-assert-us = <500>;
    reset-deassert-us = <500>;
 
    phy0: ethernet-phy@3 {
        reg = <3>;
        interrupt-parent = <&gpio>;
        interrupts = <43 1>;
    };
};
```

It means if this issue exists, u-boot will never be able to use any network boot, it can not apply the reseting before the driver probing of Phy IC because of the missed implementation. I also found a chinese blog site, [where this problem was also mentioned for Kria K26 SoM](https://www.i4k.xyz/article/jin787730090/124202102#UBoot_ETH_PHY_Reset_571). On this blog there is a code modification for u-boot to solve it.

I made a patch for [zynq_gem.c](https://github.com/Xilinx/u-boot-xlnx/blob/master/drivers/net/zynq_gem.c) and tried to use it, the result was that it is working nicely. Based on that blog site, in this pull request u-boot can parsing the same "reset-gpios" properties from device-tree and it able to do a Phy IC reset before every driver probing, then the Phy IC is ready to use on the mdio bus, and ethernet is starting to work in u-boot, too.

@michalsimek 
- Can you provide some information, what is the official way to submit this patch in to the u-boot source code of Xilinx?
- Can you review my code in this GitHub pull request? I do not think that the current version the most suitable to use, but works. I need some more help/hints, what kind of code architect can be the best to use it, for example do i need to split the device-tree properties parsing and the gpio toggling in a separted funcitons or not?

### CODE REVIEW

**Comment by michalsimek** [comment]
First of all. Pull request via github are not allowed.
Second - your patch is not the right way to go.
Use ethernet-phy-id compatible string under mdio bus and you will get reset functionality. 
Description is for example here.
https://github.com/Xilinx/u-boot-xlnx/blob/master/arch/arm/dts/zynqmp-sck-kv-g-revA.dts#L175

**Comment by Livius90** [comment]
> First of all. Pull request via github are not allowed. Second - your patch is not the right way to go. Use ethernet-phy-id compatible string under mdio bus and you will get reset functionality. Description is for example here. https://github.com/Xilinx/u-boot-xlnx/blob/master/arch/arm/dts/zynqmp-sck-kv-g-revA.dts#L175

I tried to use the following as was mentioned in the example link:
```C
&gem3 {
	phy-mode = "rgmii-id";
	phy-handle = <&phy0>;
	local-mac-address = [00 0a 35 00 22 01];
	status = "okay";
	
	phy0: ethernet-phy@3 {
		compatible = "ethernet-phy-id0022.1622";
		reg = <3>;
		
		interrupt-parent = <&gpio>;
		interrupts = <43 1>;
		
		reset-names = "phy-ksz9031";
		// reset-gpios = <&gpio 38 GPIO_ACTIVE_LOW>;
		reset-gpios = <&gpio 38 1>;
		reset-assert-us = <500>;
		reset-deassert-us = <500>;
	};
};
```

Your solution is not working, it just forcing to use Micrel ksz9031 driver in U-boot and Linux but there are no any gpio reset occurs. You can see my U-boot console, Phy IC is still in reset state, because i can not read Phy ident 1 and 2 after the booting but later when i do the gpio reset manually, Phy ident reading works. It means U-boot driver does not do anything with the gpio-reset. Unfortunately Linux does not do, also. In Linux, gpio-reset works only if it placed in gem3 node only.

```console
U-Boot 2022.01 (Sep 20 2022 - 06:35:33 +0000)

CPU:   ZynqMP
Silicon: v3
Model: Sundance PXIe800Z card
Board: Xilinx ZynqMP
DRAM:  8 GiB
PMUFW:  v1.1
PMUFW no permission to change config object
EL Level:       EL2
Chip ID:        zu7ev
NAND:  0 MiB
MMC:   mmc@ff170000: 0
Loading Environment from FAT... *** Error - No Valid Environment Area found
*** Warning - bad env area, using default environment

In:    serial
Out:   serial
Err:   serial
Bootmode: LVL_SHFT_SD_MODE1
Reset reason:   SOFT
Net:   FEC: can't find phy-handle
PHY reset timed out

ZYNQ GEM: ff0e0000, mdio bus ff0e0000, phyaddr 3, interface rgmii-id
eth0: ethernet@ff0e0000
scanning bus for devices...
SATA link 0 timeout.
SATA link 1 timeout.
AHCI 0001.0301 32 slots 2 ports 6 Gbps 0x3 impl SATA mode
flags: 64bit ncq pm clo only pmp fbss pio slum part ccc apst
starting USB...
No working controllers found
Hit any key to stop autoboot:  0
ZynqMP> mii info
ZynqMP> mdio list
eth0:
3 - Micrel ksz9031 <--> ethernet@ff0e0000
ZynqMP> mdio read 0x3 2
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
2 - 0xffff
ZynqMP> mdio read 0x3 3
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
3 - 0xffff
ZynqMP> gpio set 38
gpio: pin 38 (gpio 38) value is 1
ZynqMP> mii info
PHY 0x03: OUI = 0x0885, Model = 0x22, Rev = 0x02, 1000baseT, FDX
ZynqMP> mdio list
eth0:
3 - Micrel ksz9031 <--> ethernet@ff0e0000
ZynqMP> mdio read 0x3 2
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
2 - 0x22
ZynqMP> mdio read 0x3 3
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
3 - 0x1622
```

**Comment by michalsimek** [comment]
YOu are missing mdio node in the description. It is gem/mdio/phy.

**Comment by Livius90** [comment]
> YOu are missing mdio node in the description. It is gem/mdio/phy.

Ok, i tired the following, as you mentioned.

```C
&gem3 {
	phy-mode = "rgmii-id";
	phy-handle = <&phy0>;
	local-mac-address = [00 0a 35 00 22 01];
	status = "okay";
	
	mdio: mdio {
		#address-cells = <1>;
		#size-cells = <0>;
		
		phy0: ethernet-phy@3 {
			compatible = "ethernet-phy-id0022.1622";
			reg = <3>;
			
			interrupt-parent = <&gpio>;
			interrupts = <43 1>;
			
			reset-names = "phy-ksz9031";
			// reset-gpios = <&gpio 38 GPIO_ACTIVE_LOW>;
			reset-gpios = <&gpio 38 1>;
			reset-assert-us = <500>;
			reset-deassert-us = <500>;
		};
	};
};
```

It seems to me, that kind of nodes are ok only for u-boot. So in u-boot console i can reading the ident register of Phy IC, so the gpio-reset works in it.

```
ZynqMP> mii info
PHY 0x03: OUI = 0x0885, Model = 0x22, Rev = 0x02, 1000baseT, FDX
ZynqMP> mdio list
eth0:
3 - Micrel ksz9031 <--> ethernet@ff0e0000
ZynqMP> mdio read 0x3 2
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
2 - 0x22
ZynqMP> mdio read 0x3 3
0x3 is not a known ethernet
Reading from bus eth0
PHY at address 3:
3 - 0x1622
```

But, for Linux that node structure does not work, i think it is not compatible for Linux kernel booting. RGMII link could start but somewhy the final 1000 Mb/s link up message is missing in dmesg, and also, i can not ping the board (board has a fixed IP and my desktop PC has an other fixed IP in same subnet). For Linux i need to use gpio-reset in gem3 node directly to get a working ethernet finaly.

```console
root@ZynqMP:~# dmesg | grep eth
[    0.000000] psci: probing for conduit method from DT.
[    2.076930] usbcore: registered new interface driver cdc_ether
[    2.613155] macb ff0e0000.ethernet: Not enabling partial store and forward
[    2.625005] macb ff0e0000.ethernet eth0: Cadence GEM rev 0x50070106 at 0xff0e0000 irq 38 (00:0a:35:00:22:01)
[    8.448976] macb ff0e0000.ethernet eth0: PHY [ff0e0000.ethernet-ffffffff:03] driver [Micrel KSZ9031 Gigabit PHY] (irq=66)
[    8.449346] macb ff0e0000.ethernet eth0: configuring for phy/rgmii-id link mode
```

**Comment by Livius90** [comment]
If i use my [first device-tree node style](https://github.com/Xilinx/u-boot-xlnx/pull/51#issue-1424781066) (gpio-reset in gem3) Linux can do the reset and ethernet initialization well.

```console
root@ZynqMP:~# dmesg | grep eth
[    0.000000] psci: probing for conduit method from DT.
[    2.075395] usbcore: registered new interface driver cdc_ether
[    2.611485] macb ff0e0000.ethernet: Not enabling partial store and forward
[    2.620438] macb ff0e0000.ethernet eth0: Cadence GEM rev 0x50070106 at 0xff0e0000 irq 38 (00:0a:35:00:22:01)
[    8.326682] macb ff0e0000.ethernet eth0: PHY [ff0e0000.ethernet-ffffffff:03] driver [Generic PHY] (irq=POLL)
[    8.326708] macb ff0e0000.ethernet eth0: configuring for phy/rgmii-id link mode
[   14.480226] macb ff0e0000.ethernet eth0: Link is Up - 1Gbps/Full - flow control tx
[   14.480274] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

**Comment by Livius90** [comment]
@michalsimek 
So how can i use a same device-tree which is able to do gpio-reset well in both, U-boot and Linux kernel booting, too? What can be the solution?

**Comment by Livius90** [comment]
I could find the problem, i needed to remove interrupt gpio from my phy node, so the following device-tree node is perfect for U-boot and Linux as well.

```
&gem3 {
	phy-mode = "rgmii-id";
	phy-handle = <&phy0>;
	local-mac-address = [00 0a 35 00 22 01];
	status = "okay";
	
	mdio: mdio {
		#address-cells = <1>;
		#size-cells = <0>;
		
		phy0: ethernet-phy@3 {
			compatible = "ethernet-phy-ieee802.3-c22";
			reg = <3>;
			
			reset-names = "phy-ksz9031";
			// reset-gpios = <&gpio 38 GPIO_ACTIVE_LOW>;
			reset-gpios = <&gpio 38 1>;
			reset-assert-us = <500>;
			reset-deassert-us = <500>;
		};
	};
};
```

**Comment by michalsimek** [comment]
ethernet-phy-ieee802.3-c22 is not supported by U-Boot that's why you should check if U-Boot is really calling that gpio reset properly. I have added support for "ethernet-phy-idVVVV.DDDD" only.

**Comment by Livius90** [comment]
Documentation also mentioned to use it and when i use it, u-boot can initialize Phy IC well, i can check the iden addresses in u-boot console.
https://github.com/Xilinx/u-boot-xlnx/blob/master/doc/device-tree-bindings/net/phy.txt

**Pull request closed without merging**
