### PR TITLE
Feature/enable atags as kconfig opt

### PR DESCRIPTION
**Pull request by ehansenLMRX**

### CODE REVIEW

**Comment by michalsimek** [comment]
Why do you need to enable ATAGS?

**Comment by ehansenLMRX** [comment]
The particular version and custom BSP my clients are using requires the use of an ATAGS description format to properly initialize the Green Hills Integrity operating system. Granted, this isn't "the way" things are done anymore but they're trying to avoid having to re-code the existing software.

**Comment by ehansenLMRX** [comment]
To further add to the discussion, their version of Integrity doesn't support the use of a FDT and the boot_prep_linux function in arch/arm/lib/bootm.c requires the use/presence of either FDT or ATAGS support. Green Hills makes their OS look like a Linux image to facilitate loading.

**Comment by michalsimek** [comment]
Please send this patch to mainline u-boot with proper description.

**Pull request closed without merging**
